### ISSUE TITLE
NoSuchFieldError: STABLE

### ISSUE THREAD

**Issue by tuddman** [sunng87/ring-jetty9-adapter#28]
```
Exception in thread "main" java.lang.NoSuchFieldError: STABLE, compiling:(/private/var/folders/y2/407hjm5x30ng3787_p00l_080000gn/T/form-init8179679215271893313.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7441)
	at clojure.lang.Compiler.loadFile(Compiler.java:7367)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoSuchFieldError: STABLE
	at org.eclipse.jetty.server.Server.doStart(Server.java:373)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at ring.adapter.jetty9$run_jetty.invokeStatic(jetty9.clj:220)
	at ring.adapter.jetty9$run_jetty.invoke(jetty9.clj:163)
...
```

An older version of this library was working fine.  Now using `[info.sunng/ring-jetty9-adapter "0.10.1"]`

This might be user error, but the app I've included it into is simple, and based on the websocket `./examples/websocket.clj`.

If you've come across this?

**Comment by tuddman** [comment]
from:

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java#L374

best way to set `~jetty-version` in `project.clj`

**Comment by sunng87** [comment]
Hi @tuddman , I cannot reproduce this issue with `lein with-profile default,example-http run`, which starts a jetty server and listening on a http port.

Could you please check if there's any other version of jetty in your classpath? Your error is not `STABLE == false`, but `STABLE` field not found. This is probably caused by some other version of jetty in your classpath.

**Comment by tuddman** [comment]
@sunng87 this was misplaced. was another dependency that was bringing in older version of jetty & interfering.  set the exclusion.   thanks!
