### ISSUE TITLE
Websocket example: Wrong number of args (2)

### ISSUE THREAD

**Issue by tuddman** [sunng87/ring-jetty9-adapter#34]
steps to reproduce:
1. clone this repo.
2.  `lein with-profile default,example-websocket run`
3.  (in another terminal)    `wsc -er http://localhost:5000/path1/`
Connected to http://localhost:5000/path1/
>

entering any text (at connected prompt) produces . `ArityException:`

```
2018-07-17 19:32:12.663:WARN:rajwpejwa.WebSocketAdapterff19274a:qtp1288052401-10: Unhandled Error (closing connection)
clojure.lang.ArityException: Wrong number of args (2) passed to: websocket/eval734/fn--735
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:36)
	at ring.adapter.jetty9.websocket$eval577$fn__602$G__558__615.invoke(websocket.clj:17)
	at rj9a.websocket$fn__849.invokeStatic(websocket.clj:9)
	at rj9a.websocket$fn__849.invoke(websocket.clj:7)
	at ring.adapter.jetty9.websocket$proxy_ws_adapter$fn__757.invoke(websocket.clj:126)
	at ring.adapter.jetty9.websocket.proxy$org.eclipse.jetty.websocket.api.WebSocketAdapter$ff19274a.onWebSocketText(Unknown Source)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:476)
	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:183)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:105)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:142)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:85)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:245)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:560)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:391)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tscrowley** [comment]
I have a PR up now. 

Frustrating that `extend-protocol` syntax differs, the code compiles, and the WS arity works... I spent ages going down a ton of rabbit holes trying to figure out why the code wouldn't work.

Sorry for regression again!

**Comment by tuddman** [comment]
@tscrowley thanks!!
